receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:
  debug: {}
  # otlp:
  #   endpoint: otelcol:4317
  jaeger_storage_exporter:
    trace_storage: memstore
    queue:
      num_consumers: 10
      queue_size: 100
extensions:
  jaeger_query:
    storage:
      traces: memstore
  jaeger_storage:
    backends:
      memstore:
        memory:
          max_traces: 100000

service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, jaeger_storage_exporter]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
