services:
  jaeger:
    image: jaegertracing/jaeger:2.4.0
    container_name: jaeger
    command: 
      - '--config'
      - '/jaeger/config.yaml'
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"
    restart: always
    volumes:
      - ./jaeger-config/config.yaml:/jaeger/config.yaml:ro
